import type { Product } from "@/types";

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Royal Oud",
    price: 299,
    originalPrice: 380,
    description: "A majestic blend of rare oud wood and golden amber, crafted for royalty.",
    fullDescription: "Royal Oud is our flagship masterpiece — a profound journey into the heart of luxury. This extraordinary fragrance opens with a whisper of saffron and bergamot before revealing its magnificent soul: a complex accord of rare Cambodian oud, aged sandalwood, and Mysore rosewood. The golden base settles into warm amber, musk, and vanilla absolute, leaving an unforgettable trail of elegance. Wear it and become royalty.",
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
    ],
    category: "Oud",
    featured: true,
    discount: 21,
    inStock: true,
    rating: 5,
    notes: {
      top: ["Saffron", "Bergamot", "Cardamom"],
      middle: ["Cambodian Oud", "Rose Absolute", "Iris"],
      base: ["Amber", "Sandalwood", "Vanilla", "Musk"],
    },
    volume: "100ml",
  },
  {
    id: "2",
    name: "Golden Elixir",
    price: 249,
    originalPrice: 310,
    description: "An intoxicating fusion of jasmine, tuberose, and warm golden musk.",
    fullDescription: "Golden Elixir is a hypnotic floral oriental fragrance that captures the golden hour in a bottle. The composition opens brilliantly with Italian bergamot and pink pepper, then blooms into an opulent heart of Egyptian jasmine and tuberose. As time passes, it reveals a sensuous base of golden amber, benzoin, and white musks — creating an aura of warmth and seduction that lasts all day.",
    images: [
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
    ],
    category: "Floral",
    featured: true,
    discount: 20,
    inStock: true,
    rating: 5,
    notes: {
      top: ["Bergamot", "Pink Pepper", "Lemon Zest"],
      middle: ["Jasmine", "Tuberose", "Ylang-Ylang"],
      base: ["Golden Amber", "Benzoin", "White Musk"],
    },
    volume: "100ml",
  },
  {
    id: "3",
    name: "Midnight Crown",
    price: 329,
    description: "Dark, mysterious, and powerfully captivating — a fragrance for the bold.",
    fullDescription: "Midnight Crown is a bold oriental fragrance inspired by the power and mystique of the night. It begins with a striking blend of black pepper, dark plum, and incense, evolving into a rich heart of black rose, vetiver, and tobacco flower. The final act is an unforgettable composition of dark oud, patchouli, leather accord, and black amber — a fragrance that commands respect and leaves a lasting impression.",
    images: [
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
    ],
    category: "Oriental",
    featured: true,
    inStock: true,
    rating: 4,
    notes: {
      top: ["Black Pepper", "Dark Plum", "Incense"],
      middle: ["Black Rose", "Vetiver", "Tobacco Flower"],
      base: ["Dark Oud", "Patchouli", "Leather", "Black Amber"],
    },
    volume: "100ml",
  },
  {
    id: "4",
    name: "Rose Royale",
    price: 219,
    originalPrice: 270,
    description: "The quintessence of feminine elegance — pure Bulgarian rose on a soft musk bed.",
    fullDescription: "Rose Royale is a timeless celebration of the world's most beloved flower. Crafted with the finest Bulgarian rose absolute, this fragrance captures the dewy freshness of rose petals at dawn. The heart blooms with peony and violet leaves, while the base anchors everything in a soft embrace of musk, cedarwood, and a touch of amber. Pure, feminine, unforgettable.",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop&q=80",
    ],
    category: "Floral",
    featured: false,
    discount: 19,
    inStock: true,
    rating: 5,
    notes: {
      top: ["Raspberry", "Lychee", "Bergamot"],
      middle: ["Bulgarian Rose", "Peony", "Violet Leaf"],
      base: ["Musk", "Cedarwood", "Amber"],
    },
    volume: "100ml",
  },
  {
    id: "5",
    name: "Amber Palace",
    price: 279,
    description: "Warm, enveloping amber with rich balsamic notes — the scent of luxury at home.",
    fullDescription: "Amber Palace is an opulent oriental fragrance that wraps you in warmth like a velvet cloak. The opening is a rich spice accord — cinnamon, clove, and saffron — leading into a heart of labdanum, benzoin, and copaiba balsam. The base is a sumptuous amber accord anchored by vanilla, tonka bean, and sandalwood. This fragrance is an invitation to indulgence.",
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
    ],
    category: "Oriental",
    featured: false,
    inStock: true,
    rating: 4,
    notes: {
      top: ["Cinnamon", "Clove", "Saffron"],
      middle: ["Labdanum", "Benzoin", "Copaiba Balsam"],
      base: ["Vanilla", "Tonka Bean", "Sandalwood", "Amber"],
    },
    volume: "100ml",
  },
  {
    id: "6",
    name: "Desert Wind",
    price: 259,
    originalPrice: 320,
    description: "A captivating journey through spice markets and sandalwood forests.",
    fullDescription: "Desert Wind tells the story of ancient spice routes and desert caravans. It opens with vibrant cardamom, cumin, and coriander, evoking the warmth of desert air at sunrise. The heart reveals a rich tapestry of sandalwood, oud, and myrrh, while the base settles into a smooth accord of frankincense, benzoin, and labdanum. A fragrance that carries the soul of the ancient East.",
    images: [
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
    ],
    category: "Oud",
    featured: false,
    discount: 19,
    inStock: true,
    rating: 4,
    notes: {
      top: ["Cardamom", "Cumin", "Coriander"],
      middle: ["Sandalwood", "Oud", "Myrrh"],
      base: ["Frankincense", "Benzoin", "Labdanum"],
    },
    volume: "100ml",
  },
  {
    id: "7",
    name: "Velvet Noir",
    price: 289,
    description: "Silky smooth with an irresistible depth — black iris and dark woods.",
    fullDescription: "Velvet Noir is the definition of sophisticated sensuality. A powdery, dark fragrance that opens with cold violet leaves and aldehydes before revealing a stunning heart of black iris absolute, orris root, and smoky incense. The base is a rich accord of dark woods, vetiver, and a touch of leather, creating a fragrance that is simultaneously mysterious and deeply comforting.",
    images: [
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
    ],
    category: "Oriental",
    featured: false,
    inStock: true,
    rating: 5,
    notes: {
      top: ["Violet Leaf", "Aldehydes", "Pink Pepper"],
      middle: ["Black Iris", "Orris Root", "Incense"],
      base: ["Dark Woods", "Vetiver", "Leather", "Musk"],
    },
    volume: "100ml",
  },
  {
    id: "8",
    name: "Celestial Musk",
    price: 199,
    originalPrice: 240,
    description: "Ethereally light and sensual — clean musks with a whisper of white florals.",
    fullDescription: "Celestial Musk is the fragrance equivalent of morning light — clean, pure, and utterly captivating. It opens with a fresh accord of bergamot and white tea, evolving into a delicate heart of white flowers, lily of the valley, and magnolia. The base is an exquisite blend of clean musks, cashmere wood, and a hint of amber, creating a fragrance that is effortlessly beautiful and deeply personal.",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&h=800&fit=crop&q=80",
    ],
    category: "Floral",
    featured: false,
    discount: 17,
    inStock: true,
    rating: 4,
    notes: {
      top: ["Bergamot", "White Tea", "Green Accord"],
      middle: ["White Flowers", "Lily of the Valley", "Magnolia"],
      base: ["Clean Musk", "Cashmere Wood", "Amber"],
    },
    volume: "100ml",
  },
];

export const WHATSAPP_NUMBER = "201143304017";
export const TELEGRAM_USERNAME = "royal_perfumss";
export const ADMIN_USERNAME = "admin";
export const ADMIN_PASSWORD = "0099332211";

export const CATEGORIES = ["All", "Oud", "Floral", "Oriental"];
